version: 2.1

orbs:
  vault: contentful/vault@1

jobs:
  unit:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - run: npm run test:unit
  integration:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - run: npm run test:integration
  release:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - vault/get-secrets: # Loads vault secrets
          template-preset: "semantic-release-ecosystem"
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release
workflows:
  build_and_test:
    jobs:
      - unit
      - integration
      - release:
          context:
            - vault
          requires:
            - unit
            - integration
